#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "mollysocket"
name = "Mollysocket"
description.en = "Server for unified push support in Molly chat application"
description.fr = "Serveur pour le support de unified push dans l’application de discussions Molly"

version = "1.7.1~ynh1"

maintainers = ["mcmic"]

[upstream]
license = "AGPL-3.0-or-later" # you can see the available licenses identifiers list here: https://spdx.org/licenses/
website = "https://molly.im/"
admindoc = "https://github.com/mollyim/mollysocket/blob/main/README.md"
code = "https://github.com/mollyim/mollysocket"

fund = "https://opencollective.com/mollyim"

[integration]
yunohost = ">= 12.0.0"
helpers_version = "2.1"
architectures = ["amd64","armhf","arm64"]
multi_instance = true

ldap = "not_relevant"
sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.allowed_endpoints]
    ask = "the URL of the UnifiedPush server that can forward notifications; leave as `*` if you don't want to limit which UP servers can use this instance of mollysocket"
    help = "https://my.domain.tld"
    type = "string"
    default = "*"

[resources]

    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/mollyim/mollysocket/releases/download/1.7.1/mollysocket-linux_amd64"
    amd64.sha256 = "09fa591aa732aac1ad7a16f71107b7a8e7ba9b01abcee25e9c66203818bc7bfd"
    arm64.url = "https://github.com/mollyim/mollysocket/releases/download/1.7.1/mollysocket-linux_arm64"
    arm64.sha256 = "2503185626d735c2482a71104510fae070f804cff2d4a8b0aaf4022b36047bbd"
    armhf.url = "https://github.com/mollyim/mollysocket/releases/download/1.7.1/mollysocket-linux_arm_v7"
    armhf.sha256 = "6035cc9b0b07881c84a28dec61d8b7353aafdaef663eeeb8e9270d809e39e90c"
    rename = "ms"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "mollysocket-linux_amd64"
    autoupdate.asset.arm64 = "mollysocket-linux_arm64"
    autoupdate.asset.armhf = "mollysocket-linux_arm_v7"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.show_tile = false
    main.allowed = "visitors"

    [resources.ports]
