#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

chown -R "$app:$app" "$install_dir"
chmod +x "$install_dir/ms"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

#vapidkey=$($install_dir/ms vapid gen)
$install_dir/ms vapid gen | systemd-creds encrypt --name=vapid.key - $install_dir/vapid.key

chmod 600 "$install_dir/vapid.key"
chown "$app:$app" "$install_dir/vapid.key"

ynh_config_add --template="conf.toml" --destination="$install_dir/conf.toml"

chmod 400 "$install_dir/conf.toml"
chown "$app:$app" "$install_dir/conf.toml"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Mollysocket push server" --log="/var/log/$app/$app.log"

mkdir -p /var/log/$app
touch /var/log/$app/$app.log

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="/var/log/$app/$app.log" --wait_until="Rocket has launched from"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app complete."
