#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="conf.toml mollysocket.db"

chown -R "$app:$app" "$install_dir"
chmod +x "$install_dir/ms"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Mollysocket push server" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="/var/log/$app/$app.log" --wait_until="Rocket has launched from"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app complete."
